### ISSUE TITLE
How to install in airgap environment? 

### ISSUE THREAD

**Issue by sreerammc** [kubecfg/kubit#472]
Hi there,

I am new to Kubit. Any pointer is well appreciated. 

I need to install Kubit on to a private AKS or on jump server that is not connected to internet. Can any one please advise, how I can install this on client jump system or on AKS without internet connection?

Regards,
Sreeram

**Comment by jdockerty** [comment]
Installing `kubit` (or any external software) into an airgapped environment will be dependent on your own/organisation's requirements.

It is likely you will have to retrieve the image of `kubit` you want to use and copy it into an internal registry which is accessible by your AKS cluster.
